### ISSUE TITLE
problem with dock icons

### ISSUE THREAD

**Issue by mickey-megabyte** [robint99/dock-applet#1]
Hi - this is my first bug report on github, so apologies if I don't do it correctly!

![doc problem](https://cloud.githubusercontent.com/assets/6961084/7642991/447f09ec-fa8d-11e4-9df9-7123bbc61542.png)

Top part of image is what i see with my mate panel set to autohide - bottom half is how they should look.

Ubuntu mate 15.04  
Intel integrated graphics
X.org 1.17.1

Dock-applet works fine on my desktop running the same OS (but with open-source AMD graphics driver)

I am willing to supply you with more information if you need it.

Thanks for your applet - it's very useful!

mickey

**Comment by robint99** [comment]
Hi,

I suspect that this could be a graphics driver issue. On my desktop (Arch with Nvidia  closed source drivers) everything works ok. On my laptop (Ubuntu Mate 15.04 with AMD closed source drivers) everything works ok as well. Unfortunately I don't have any hardware with integrated intel graphics to run any tests on

If you can spare the time there are a few things you can do to confirm my suspicions:

**Comment by mickey-megabyte** [comment]
sure - what do you want me to do?

**Comment by robint99** [comment]
See above, I accidentally submitted my comment half-finished...

**Comment by mickey-megabyte** [comment]
OK

other applets don't have the problem

compiz seem to fix the problem  (but don't really want to run compiz - i think it affects battery life), but gives a new problem with white vertical lines

as far as i know, intel released the open source drivers themselves - no closed source available from 'additional drivers'

output of lspci:  00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

I've noticed another problem too - when opening terminal from dock applet, it starts off in / (root) rather than ~ (home)  (happens on laptop and desktop) 

should i submit a new issue?

**Comment by mickey-megabyte** [comment]
sorry - here are the white vertical lines i mentioned with compiz

![lines](https://cloud.githubusercontent.com/assets/6961084/7652537/85aeb6a6-fb05-11e4-8e0a-9147fc892776.png)

**Comment by robint99** [comment]
Ok, thanks for doing all that. Don't worry about submitting a new issue, I'll look at both things together and hopefully get them sorted at the same time.

And thanks again for your help, much appreciated!

**Comment by mickey-megabyte** [comment]
any time - i'm available for any further testing if you need me  :)

**Comment by abrowne** [comment]
I've noticed the same (or similar) issue when running in Ubuntu Mate 15.04 in Virtualbox.

**Comment by robint99** [comment]
Thanks abrowne. I installed Mate 15.04 in VirtualBox and after having a bit of a play around with the settings have been able to duplicate the problem. and on real hardware (my laptop). It seems it only occurs when you don't have a compositing window manager running.

I'll start working on a fix straight away, but in the meantime an easy workaround is to simply go into system settings, click on 'Windows' and enable the software compositing window manager. This has worked for me on both my laptop and in Virtualbox.

Cheers,

Robin

**Comment by abrowne** [comment]
I forgot I was trying it in a nearly fresh install, and I hadn't enabled
compositing yet. Thanks for the response and for creating this plugin.

On Mon, May 18, 2015 at 8:49 AM, robint99 <notifications@github.com> wrote:

> Thanks abrowne. I installed Mate 15.04 in VirtualBox and after having a
> bit of a play around with the settings have been able to duplicate the
> problem. and on real hardware (my laptop). It seems it only occurs when you
> don't have a compositing window manager running.
>
> I'll start working on a fix straight away, but in the meantime an easy
> workaround is to simply go into system settings, click on 'Windows' and
> enable the software compositing window manager. This has worked for me on
> both my laptop and in Virtualbox.
>
> Cheers,
>
> Robin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robint99/dock-applet/issues/1#issuecomment-103066431>.
>



-- 
Alexander Browne

**Comment by mickey-megabyte** [comment]
default terminal directory problem seems to be fixed.

thanks!

**Comment by robint99** [comment]
I've just uploaded V0.61 of the applet to git and the AUR and this should fix the drawing issues on non-composited screens. Hopefully the Webupd8 PPA will be updated shortly..

**Comment by freed00m** [comment]
v0.61 the problems is still present. If you disable a Software windows compositing in Linux mint 17.1 MATE
So when Compiz or Marco is taking care of desktop the problem is not there.

**Comment by robint99** [comment]
Just tried it on my laptop (Ubuntu) and it's working there. Weird! I'll give it a go on Mint VM, but even if it works, I'll tweak the drawing code again for the next version.

**Comment by mickey-megabyte** [comment]
problem still remains with 0.61 using marco with compositing switched off, ubuntu mate 15.04

**Comment by SamuelMiller** [comment]
I, too, still have problem with the icons not showing properly on autohide without compositing, even though I have updated the dock to 0.61. I am using Linux Mint Mate 17.1 on an Aspire One netbook with Intel integrated graphics.

**Comment by karas84** [comment]
I have a similiar issue, but I'm using no composing since I'm on an xrdp remote session:

![artifacts](https://cloud.githubusercontent.com/assets/9134935/8104164/d9785b6e-102e-11e5-82ed-7b4811f44cd7.jpg)

This happens only when I minimize windows.

**Comment by robint99** [comment]
I've been working on a fix for the redrawing issue and it'll be included in
the next version of the applet. Before then, I'll check that it works over
rdp too...

Cheers

**Comment by robint99** [comment]
I've just uploaded a new version of the applet to github, which should fix all redrawing issues (both local and remote). Hopefully it won't be too long before the PPA gets updated and you can try it out :)

**Comment by karas84** [comment]
Updated from ppa, working nicely. Thank You!
Today I noticed something strange, when opening [matlab](http://www.mathworks.com) I can't see no icon on your dock. It's fine on other docks though.

**Comment by robint99** [comment]
There's been a problem with matlab for a while - see the issue regarding
Java programs. I was hoping the latest version of the applet might have
fixed it but instead it seems to have made things worse ;)

Unfortunately I don't have a copy of matlab for testing (I registered an an
account and they wouldn't let have a trial version for some reason) but
I'll see what I can do to get hold of one so I can nail this problem once
and for all.

Good to hear your drawing issues are fixed though!

**Comment by karas84** [comment]
I suppose you already tried [here](http://www.mathworks.com/programs/trials/trial_request.html). I already have an academic license so I can't try it myself.

**Comment by robint99** [comment]
Yes, that's where I tried. My mistake was clicking the box that said I
wanted it for non-commercial purposes. They didn't seem to like that...

I think what I'll do is register again with a different email address, try
a different option this time and see if I can get a download that way.

**Comment by robint99** [comment]
Hi Karas, 

I managed to get hold of a trial version of Matlab 2015a and it seems to work ok with the applet once a custom launcher has been created. This was on Linux Mint 17.1. To help me sort out your problem could you let me know what distro you're using (e.g. Ubuntu Mate 14.04, 14.10 or 15.04) so that I can try it for myself. 

Also I'm going to close this issue as it relates to the drawing issues which now seem to be fixed, so could you reply in the issue regarding Java programs. 

Thanks!
